// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.installation.timestamp", "132942744605849915");
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.lastInstalledTaskVersion", 3);
user_pref("app.update.background.rolledout", true);
user_pref("app.update.backgroundErrors", 1);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1649807208);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1649803988);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1649803970);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1649807745);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1649804108);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1649807773);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1649804019);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir3.E7CF176E110C211B", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{57000237-e03c-47e5-98b4-513f0843c1bd}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1649803958);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 125);
user_pref("browser.newtabpage.activity-stream.impressionId", "{daee510d-ded9-4503-a0ee-3310c87a8961}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20220330194208");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1649807745");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20220330194208");
user_pref("browser.startup.homepage_override.mstone", "99.0");
user_pref("browser.startup.lastColdStartupCheck", 1649807745);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1649803966365");
user_pref("distribution.iniFile.exists.appversion", "99.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220330194208");
user_pref("extensions.lastAppVersion", "99.0");
user_pref("extensions.lastPlatformVersion", "99.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"a0955f49-f81a-42d2-b2af-cf73284fa6a3\",\"formautofill@mozilla.org\":\"661fcac7-7456-40b3-9aa7-30f0705118cb\",\"pictureinpicture@mozilla.org\":\"cd367f62-bffd-4cfd-b0a9-86281fce839b\",\"screenshots@mozilla.org\":\"7272cb4c-a895-4eed-bab0-7f72e8be00e5\",\"webcompat-reporter@mozilla.org\":\"f5f5170a-f85e-40ad-9449-9d61cbe8aeba\",\"webcompat@mozilla.org\":\"00fec663-695b-42b2-b9b5-90861c61498a\",\"default-theme@mozilla.org\":\"25105e4a-4e83-45f3-b104-aa07691a32c1\",\"addons-search-detection@mozilla.com\":\"a0de23cc-5d8e-4b08-ac91-6f825cc2f8c8\",\"google@search.mozilla.org\":\"89a5674e-2baa-4d9f-a8e9-0eb2a09d8fa3\",\"amazondotcom@search.mozilla.org\":\"491c9618-11f2-43fc-9721-ff249498b3f2\",\"wikipedia@search.mozilla.org\":\"7ee66cfd-22ed-4bce-9531-424845d9e025\",\"bing@search.mozilla.org\":\"c97ea631-4a0e-4abc-a99a-fb9a6550a596\",\"ddg@search.mozilla.org\":\"50943384-1548-4fcc-8efc-95c90f8e76a4\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1649803972);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-manager.buildID", "20220330194208");
user_pref("media.gmp-manager.lastCheck", 1649804078);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.device-id", "0x0405");
user_pref("sanity-test.driver-version", "8.16.7.5");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20220330194208");
user_pref("security.sandbox.content.tempDirSuffix", "{6df14e0c-eeb7-4915-9133-039aa7464ad0}");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1649807741);
user_pref("toolkit.telemetry.cachedClientID", "8ef50ddf-91e8-41eb-8801-6884ce4afaa7");
user_pref("toolkit.telemetry.previousBuildID", "20220330194208");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
